# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Aruna' do
  pod 'AppCenter/Crashes', '~> 2.5.0'
  pod 'AppCenter/Analytics', '~> 2.5.0'
  pod 'AppCenterReactNativeShared', '~> 2.5.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Aruna

  

  platform :ios, '9.0'
  target 'ArunaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Aruna-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Aruna-tvOS

  target 'Aruna-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
